//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeFunding.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cause
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Website { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string StellarAddress { get; set; }
        public string Photo { get; set; }
        public double FundGoal { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public double AmountAchieved { get; set; }
    }
}
